# Generated by Django 5.2.5 on 2025-09-23 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicobusca',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicobusca',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicobusca',
            name='tipo',
            field=models.CharField(choices=[('search', 'Busca'), ('view', 'Visualização'), ('favorite', 'Favorito'), ('message', 'Mensagem')], default='search', max_length=20, verbose_name='Tipo de Atividade'),
        ),
        migrations.AlterField(
            model_name='historicobusca',
            name='categoria_ct',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'produtos', 'model': 'categoria'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_categoria', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='historicobusca',
            name='termo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
