# Generated by Django 5.2.5 on 2025-11-23 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('produtos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postagemproduto',
            name='produto_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.anuncio'),
        ),
        migrations.AddField(
            model_name='midiapostagem',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='core.postagemproduto'),
        ),
        migrations.AddField(
            model_name='curtidapostagem',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='core.postagemproduto'),
        ),
        migrations.AddField(
            model_name='seguidorpagina',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='core.paginapessoal'),
        ),
        migrations.AddField(
            model_name='seguidorpagina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo_paginas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['content_type', 'object_id'], name='core_favori_content_b4d408_idx'),
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['usuario', 'data_criacao'], name='core_favori_usuario_6ca782_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='historicobusca',
            index=models.Index(fields=['usuario', 'data_busca'], name='core_histor_usuario_1074be_idx'),
        ),
        migrations.AddIndex(
            model_name='historicobusca',
            index=models.Index(fields=['termo'], name='core_histor_termo_a8a415_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='core_custom_email_a5d01e_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['nome_utilizador'], name='core_custom_nome_ut_f4b9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['cpf'], name='core_custom_cpf_00993c_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['conversa_id'], name='core_mensag_convers_33d5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['remetente', 'destinatario'], name='core_mensag_remeten_b2f526_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['data_envio'], name='core_mensag_data_en_0c2cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['usuario', 'lida'], name='core_notifi_usuario_cd404b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curtidapostagem',
            unique_together={('postagem', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='seguidorpagina',
            unique_together={('pagina', 'usuario')},
        ),
    ]
