# Generated by Django 5.2.5 on 2025-11-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicobusca_content_type_historicobusca_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='termos_aceitos',
            field=models.BooleanField(default=False, verbose_name='Termos Aceitos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nome',
            field=models.CharField(help_text='Seu nome completo como deseja ser chamado', max_length=255, verbose_name='Nome Completo'),
        ),
    ]
