# Generated by Django 5.2.5 on 2025-11-13 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_termos_aceitos_alter_customuser_nome'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pagina_criada',
            field=models.BooleanField(default=False, verbose_name='Página Pessoal Criada'),
        ),
        migrations.CreateModel(
            name='PaginaPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pagina', models.CharField(help_text='Nome único para sua página pessoal', max_length=100, unique=True, verbose_name='Nome da Página')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug da Página')),
                ('bio', models.TextField(blank=True, help_text='Conte um pouco sobre você e seus produtos', max_length=500, verbose_name='Biografia')),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='paginas/capas/', verbose_name='Foto de Capa')),
                ('visibilidade', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('seguidores', 'Apenas Seguidores')], default='publico', max_length=20, verbose_name='Visibilidade da Página')),
                ('ativa', models.BooleanField(default=True, verbose_name='Página Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagina_pessoal', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Página Pessoal',
                'verbose_name_plural': 'Páginas Pessoais',
                'ordering': ['nome_pagina'],
            },
        ),
        migrations.CreateModel(
            name='PostagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True, max_length=2200)),
                ('hashtags', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('curtidas_count', models.PositiveIntegerField(default=0)),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localizacao')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='core.paginapessoal')),
                ('produto_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.anuncio')),
            ],
            options={
                'verbose_name': 'Postagem de Produto',
                'verbose_name_plural': 'Postagens de Produtos',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='MidiaPostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='postagens/midias/')),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], max_length=10)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='core.postagemproduto')),
            ],
            options={
                'verbose_name': 'Mídia de Postagem',
                'verbose_name_plural': 'Mídias de Postagens',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='CurtidaPostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_postagens', to=settings.AUTH_USER_MODEL)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='core.postagemproduto')),
            ],
            options={
                'verbose_name': 'Curtida de Postagem',
                'verbose_name_plural': 'Curtidas de Postagens',
                'unique_together': {('postagem', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='SeguidorPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_seguimento', models.DateTimeField(auto_now_add=True)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='core.paginapessoal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo_paginas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguidor de Página',
                'verbose_name_plural': 'Seguidores de Páginas',
                'unique_together': {('pagina', 'usuario')},
            },
        ),
    ]
