# Generated by Django 5.2.5 on 2025-11-24 00:38

import django.core.validators
import django.db.models.deletion
import produtos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da categoria (máx. 100 caracteres)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Identificador único para URLs (gerado automaticamente)', max_length=100, unique=True, verbose_name='Slug')),
                ('imagem', models.ImageField(help_text='Imagem representativa da categoria (max 5MB)', upload_to=produtos.models.upload_to_categorias, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), produtos.models.validate_image_size], verbose_name='Ícone/Imagem')),
                ('destaque', models.BooleanField(default=False, help_text='Se a categoria aparece na página inicial', verbose_name='Destaque na Home')),
                ('ordem_menu', models.PositiveSmallIntegerField(default=99, help_text='Ordem de exibição no menu (menor número aparece primeiro)', verbose_name='Ordem no Menu')),
                ('ativa', models.BooleanField(default=True, help_text='Se a categoria está ativa e visível', verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem_menu', 'titulo'],
                'indexes': [models.Index(fields=['slug'], name='produtos_ca_slug_41ebd5_idx'), models.Index(fields=['destaque'], name='produtos_ca_destaqu_02371b_idx'), models.Index(fields=['ativa'], name='produtos_ca_ativa_b4d2f8_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug',), name='unique_categoria_slug')],
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do item (máx. 200 caracteres)', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título')),
                ('descricao', models.TextField(help_text='Descrição completa do item (máx. 2000 caracteres)', max_length=2000, verbose_name='Descrição Detalhada')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor em R$ (use . para decimais)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pendente', 'Pendente'), ('finalizado', 'Finalizado'), ('desativado', 'Desativado')], default='ativo', max_length=20, verbose_name='Status')),
                ('visualizacoes', models.PositiveIntegerField(default=0, editable=False, verbose_name='Visualizações')),
                ('whatsapp', models.CharField(blank=True, help_text='Número para contato via WhatsApp (com DDD)', max_length=20, verbose_name='WhatsApp para Contato')),
                ('estado_produto', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado - Em bom estado'), ('usado_avariado', 'Usado - Com avarias')], default='novo', max_length=20, verbose_name='Estado do Produto')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade Disponível')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca/Fabricante')),
                ('garantia', models.PositiveSmallIntegerField(default=0, help_text='Tempo de garantia em meses (0 para sem garantia)', verbose_name='Garantia (meses)')),
                ('destaque', models.BooleanField(default=False, help_text='Aparece em posições destacadas no site', verbose_name='Anúncio em Destaque')),
                ('localizacao', models.ForeignKey(blank=True, help_text='Localização principal do item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localizacao', verbose_name='Localização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('categoria', models.ForeignKey(help_text='Categoria principal do item', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='produtos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['-data_criacao'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do item (máx. 200 caracteres)', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título')),
                ('descricao', models.TextField(help_text='Descrição completa do item (máx. 2000 caracteres)', max_length=2000, verbose_name='Descrição Detalhada')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor em R$ (use . para decimais)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pendente', 'Pendente'), ('finalizado', 'Finalizado'), ('desativado', 'Desativado')], default='ativo', max_length=20, verbose_name='Status')),
                ('visualizacoes', models.PositiveIntegerField(default=0, editable=False, verbose_name='Visualizações')),
                ('whatsapp', models.CharField(blank=True, help_text='Número para contato via WhatsApp (com DDD)', max_length=20, verbose_name='WhatsApp para Contato')),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('misto', 'Misto')], default='presencial', max_length=20, verbose_name='Tipo de Serviço')),
                ('destaque', models.BooleanField(default=False, help_text='Aparece em posições destacadas no site', verbose_name='Serviço em Destaque')),
                ('disponivel_24h', models.BooleanField(default=False, verbose_name='Disponível 24h')),
                ('tempo_entrega', models.PositiveSmallIntegerField(blank=True, help_text='Tempo estimado para entrega do serviço', null=True, verbose_name='Tempo de Entrega (dias)')),
                ('categoria', models.ForeignKey(help_text='Categoria principal do item', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='produtos.categoria', verbose_name='Categoria')),
                ('localizacao', models.ForeignKey(blank=True, help_text='Localização principal do item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localizacao', verbose_name='Localização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-data_criacao'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Imagem do item (max 5MB)', upload_to=produtos.models.upload_to_imagens, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), produtos.models.validate_image_size], verbose_name='Imagem')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem para exibição das imagens (menor aparece primeiro)', verbose_name='Ordem de Exibição')),
                ('capa', models.BooleanField(default=False, help_text='Se esta é a imagem principal do item', verbose_name='Imagem Principal')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('anuncio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produtos.anuncio')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='produtos.servico')),
            ],
            options={
                'verbose_name': 'Imagem do Item',
                'verbose_name_plural': 'Imagens dos Itens',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Nota (0-5)')),
                ('comentario', models.TextField(blank=True, help_text='Comentário sobre o item (máx. 500 caracteres)', max_length=500, null=True, verbose_name='Comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('object_id', models.PositiveIntegerField()),
                ('resposta', models.TextField(blank=True, max_length=500, null=True, verbose_name='Resposta do Vendedor')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('aprovada', models.BooleanField(default=False, help_text='Se a avaliação foi aprovada para exibição', verbose_name='Aprovada')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['servico', 'anuncio']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario_avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Avaliador')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='produtos_av_content_02b79d_idx'), models.Index(fields=['aprovada'], name='produtos_av_aprovad_4e9f2b_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario_avaliador', 'content_type', 'object_id'), name='unique_avaliacao_por_item')],
            },
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['estado_produto'], name='produtos_an_estado__50fd4a_idx'),
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['quantidade'], name='produtos_an_quantid_ab5e20_idx'),
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['marca'], name='produtos_an_marca_861202_idx'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['tipo'], name='produtos_se_tipo_e20ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['destaque'], name='produtos_se_destaqu_7aa6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='servico',
            index=models.Index(fields=['usuario', 'status'], name='produtos_se_usuario_43c30e_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anuncio__isnull', True), ('servico__isnull', False)), models.Q(('anuncio__isnull', False), ('servico__isnull', True)), _connector='OR'), name='imagem_linked_to_one_item_only'),
        ),
        migrations.AddConstraint(
            model_name='imagem',
            constraint=models.UniqueConstraint(fields=('servico', 'capa'), name='unique_capa_servico'),
        ),
        migrations.AddConstraint(
            model_name='imagem',
            constraint=models.UniqueConstraint(fields=('anuncio', 'capa'), name='unique_capa_anuncio'),
        ),
    ]
