# Generated by Django 5.2.5 on 2025-11-24 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('is_group', models.BooleanField(default=False)),
                ('nome_grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_grupo', models.ImageField(blank=True, null=True, upload_to='chat_grupos/')),
                ('participantes', models.ManyToManyField(related_name='chats_participados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('localizacao', 'Localização'), ('arquivo', 'Arquivo'), ('contato', 'Contato')], default='texto', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='mensagens/')),
                ('duracao_audio', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(blank=True, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('excluida', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat', to='chat.chat')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat_enviadas', to=settings.AUTH_USER_MODEL)),
                ('respondendo_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='chat.mensagemchat')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['data_envio'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='ultima_mensagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_ultima_mensagem', to='chat.mensagemchat'),
        ),
        migrations.CreateModel(
            name='MensagemVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='chat.mensagemchat')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visualização de Mensagem',
                'verbose_name_plural': 'Visualizações de Mensagens',
            },
        ),
        migrations.AddIndex(
            model_name='mensagemchat',
            index=models.Index(fields=['chat', 'data_envio'], name='chat_mensag_chat_id_9df218_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagemchat',
            index=models.Index(fields=['remetente', 'data_envio'], name='chat_mensag_remeten_8846fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mensagemvisualizacao',
            unique_together={('mensagem', 'usuario')},
        ),
    ]
