# Generated by Django 5.2.5 on 2025-11-24 00:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('is_group', models.BooleanField(default=False)),
                ('nome_grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_grupo', models.ImageField(blank=True, null=True, upload_to='chat_grupos/')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('localizacao', 'Localização'), ('arquivo', 'Arquivo'), ('contato', 'Contato')], default='texto', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='mensagens/')),
                ('duracao_audio', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_edicao', models.DateTimeField(blank=True, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('excluida', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['data_envio'],
            },
        ),
        migrations.CreateModel(
            name='MensagemVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
