# Generated by Django 5.2.5 on 2025-09-18 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['data_envio']},
        ),
        migrations.AddField(
            model_name='chat',
            name='foto_grupo',
            field=models.ImageField(blank=True, null=True, upload_to='chat_grupos/'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='nome_grupo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='ultima_mensagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_ultima_mensagem', to='chat.mensagem'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='mensagens/'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='data_edicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='duracao_audio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='excluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='lida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='respondendo_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='chat.mensagem'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('localizacao', 'Localização'), ('arquivo', 'Arquivo'), ('contato', 'Contato')], default='texto', max_length=20),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat', to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat_enviada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['chat', 'data_envio'], name='chat_mensag_chat_id_3b84d1_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['remetente', 'data_envio'], name='chat_mensag_remeten_03a8e9_idx'),
        ),
        migrations.AddField(
            model_name='mensagemvisualizacao',
            name='mensagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='chat.mensagem'),
        ),
        migrations.AddField(
            model_name='mensagemvisualizacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mensagemvisualizacao',
            unique_together={('mensagem', 'usuario')},
        ),
    ]
