# Generated by Django 5.2.5 on 2025-11-24 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='participantes',
            field=models.ManyToManyField(related_name='chats_participados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat_enviada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='respondendo_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='chat.mensagem'),
        ),
        migrations.AddField(
            model_name='chat',
            name='ultima_mensagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_ultima_mensagem', to='chat.mensagem'),
        ),
        migrations.AddField(
            model_name='mensagemvisualizacao',
            name='mensagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='chat.mensagem'),
        ),
        migrations.AddField(
            model_name='mensagemvisualizacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['chat', 'data_envio'], name='chat_mensag_chat_id_3b84d1_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['remetente', 'data_envio'], name='chat_mensag_remeten_03a8e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mensagemvisualizacao',
            unique_together={('mensagem', 'usuario')},
        ),
    ]
