from django.urls import path
from .views import ( 
    CategoriaListView,
    AnuncioListCreateView,
    AnuncioDetailView,
    MeusAnunciosListView,
    AnunciosPorCategoriaView,
    ImagemAnuncioCreateView,
    categorias_api,
    anuncios_destaque_api,
    anuncios_recentes_api,
    home_data_api,
    categorias_list_simple,
    anuncios_por_categoria_api, 
)

urlpatterns = [
    path('categorias/', CategoriaListView.as_view(), name='categoria-list'),
    path('anuncios/', AnuncioListCreateView.as_view(), name='anuncio-list-create'),
    path('anuncios/meus/', MeusAnunciosListView.as_view(), name='meus-anuncios'),
    path('anuncios/<int:pk>/', AnuncioDetailView.as_view(), name='anuncio-detail'),
    path('anuncios/<int:anuncio_id>/imagens/', ImagemAnuncioCreateView.as_view(), name='anuncio-imagem-create'),
    path('categorias/<slug:slug>/', AnunciosPorCategoriaView.as_view(), name='anuncios-por-categoria'),
        path('categorias/', CategoriaListView.as_view(), name='categoria-list'),
    path('anuncios/', AnuncioListCreateView.as_view(), name='anuncio-list-create'),
    path('anuncios/meus/', MeusAnunciosListView.as_view(), name='meus-anuncios'),
    path('anuncios/<int:pk>/', AnuncioDetailView.as_view(), name='anuncio-detail'),
    path('anuncios/<int:anuncio_id>/imagens/', ImagemAnuncioCreateView.as_view(), name='anuncio-imagem-create'),
    path('categorias/<slug:slug>/', AnunciosPorCategoriaView.as_view(), name='anuncios-por-categoria'),
    path('categorias/api/', categorias_api, name='api-categorias'),
    path('anuncios/destaque/', anuncios_destaque_api, name='api-anuncios-destaque'),
    path('anuncios/recentes/', anuncios_recentes_api, name='api-anuncios-recentes'),
    path('home/data/', home_data_api, name='api-home-data'),
    path('anuncios/destaque/', anuncios_destaque_api, name='api-anuncios-destaque'),
    path('anuncios/recentes/', anuncios_recentes_api, name='api-anuncios-recentes'),
    path('home/data/', home_data_api, name='api-home-data'),
    path('categorias/api/', categorias_list_simple, name='api-categorias-simple'),
    path('categorias/<slug:slug>/anuncios/', anuncios_por_categoria_api, name='api-anuncios-por-categoria'),
]